
function loadAssets() {
    return {
        tornado: loadImage("assets/pixel-tornado.gif"),
        skins: {
            skinFlagBearerYecatsmailbox: loadImage("assets/skins/skinFlagBearerYecatsmailbox.gif"),
            skinFlagBearerYecatsx: loadImage("assets/skins/skinFlagBearerYecatsx.gif"),
            skinFullAmazonYecatsx: loadImage("assets/skins/skinFullAmazonYecatsx.gif"),
            skinFullArcherYecatsmailbox: loadImage("assets/skins/skinFullArcherYecatsmailbox.gif"),
            skinFullArcherYecatsmailboxHalloween: loadImage("assets/skins/skinFullArcherYecatsmailboxHalloween.gif"),
            skinFullArtilleryYecatsx: loadImage("assets/skins/skinFullArtilleryYecatsx.gif"),
            skinFullBarbarianYecatsmailbox: loadImage("assets/skins/skinFullBarbarianYecatsmailbox.gif"),
            skinFullBarbarianYecatsmailboxGold: loadImage("assets/skins/skinFullBarbarianYecatsmailboxGold.gif"),
            skinFullBarbarianYecatsxSpring23: loadImage("assets/skins/skinFullBarbarianYecatsxSpring23.gif"),
            skinFullBerserkerYecatsx: loadImage("assets/skins/skinFullBerserkerYecatsx.gif"),
            skinFullBlobYecatsx: loadImage("assets/skins/skinFullBlobYecatsx.gif"),
            skinFullBomberYecatsx: loadImage("assets/skins/skinFullBomberYecatsx.gif"),
            skinFullBusterYecatsX: loadImage("assets/skins/skinFullBusterYecatsX.gif"),
            SkinFullBusterYecatsxHoloP: loadImage("assets/skins/SkinFullBusterYecatsxHoloP.gif"),
            skinFullCenturionYecatsx: loadImage("assets/skins/skinFullCenturionYecatsx.gif"),
            skinFullFairyYecatsx: loadImage("assets/skins/skinFullFairyYecatsx.gif"),
            skinFullFlyingRogueYecatsmailbox: loadImage("assets/skins/skinFullFlyingRogueYecatsmailbox.gif"),
            skinFullGladiatorYecatsmailbox: loadImage("assets/skins/skinFullGladiatorYecatsmailbox.gif"),
            skinFullHealerYecatsx: loadImage("assets/skins/skinFullHealerYecatsx.gif"),
            skinFullLancerYecatsX: loadImage("assets/skins/skinFullLancerYecatsX.gif"),
            skinFullMonkYecatsx: loadImage("assets/skins/skinFullMonkYecatsx.gif"),
            skinFullMusketeerYecatsx: loadImage("assets/skins/skinFullMusketeerYecatsx.gif"),
            skinFullNecromancerYecatsx: loadImage("assets/skins/skinFullNecromancerYecatsx.gif"),
            skinFullPaladinYecatsx: loadImage("assets/skins/skinFullPaladinYecatsx.gif"),
            skinFullRogueYecatsmailbox: loadImage("assets/skins/skinFullRogueYecatsmailbox.gif"),
            skinFullRogueYecatsmailboxWinter: loadImage("assets/skins/skinFullRogueYecatsmailboxWinter.gif"),
            skinFullSaintYecatsx: loadImage("assets/skins/skinFullSaintYecatsx.gif"),
            skinFullShinobiYecatsx: loadImage("assets/skins/skinFullShinobiYecatsx.gif"),
            skinFullShinobiYecatsxFall23: loadImage("assets/skins/skinFullShinobiYecatsxFall23.gif"),
            skinFullTankYecatsmailbox: loadImage("assets/skins/skinFullTankYecatsmailbox.gif"),
            skinFullTemplarYecatsmailbox: loadImage("assets/skins/skinFullTemplarYecatsmailbox.gif"),
            skinFullVampireYecatsX: loadImage("assets/skins/skinFullVampireYecatsX.gif"),
            skinFullWarBeastYecatsmailbox: loadImage("assets/skins/skinFullWarBeastYecatsmailbox.gif"),
            skinFullWarriorYecatsmailbox: loadImage("assets/skins/skinFullWarriorYecatsmailbox.gif"),
            skinHeadArcherYecatsmailbox: loadImage("assets/skins/skinHeadArcherYecatsmailbox.gif"),
            skinHeadBarbarianYecatsmailbox: loadImage("assets/skins/skinHeadBarbarianYecatsmailbox.gif"),
            skinHeadBerserkerYecatsmailbox: loadImage("assets/skins/skinHeadBerserkerYecatsmailbox.gif"),
            skinHeadBomberYecatsmailbox: loadImage("assets/skins/skinHeadBomberYecatsmailbox.gif"),
            skinHeadCenturionYecatsmailbox: loadImage("assets/skins/skinHeadCenturionYecatsmailbox.gif"),
            skinHeadFlyingRogueYecatsmailbox: loadImage("assets/skins/skinHeadFlyingRogueYecatsmailbox.gif"),
            skinHeadHealerYecatsmailbox: loadImage("assets/skins/skinHeadHealerYecatsmailbox.gif"),
            skinHeadMageYecatsmailbox: loadImage("assets/skins/skinHeadMageYecatsmailbox.gif"),
            skinHeadMonkYecatsmailbox: loadImage("assets/skins/skinHeadMonkYecatsmailbox.gif"),
            skinHeadMusketeerYecatsmailbox: loadImage("assets/skins/skinHeadMusketeerYecatsmailbox.gif"),
            skinHeadPaladinYecatsmailbox: loadImage("assets/skins/skinHeadPaladinYecatsmailbox.gif"),
            skinHeadRogueYecatsmailbox: loadImage("assets/skins/skinHeadRogueYecatsmailbox.gif"),
            skinHeadTankYecatsmailbox: loadImage("assets/skins/skinHeadTankYecatsmailbox.gif"),
            skinHeadWarriorYecatsmailbox: loadImage("assets/skins/skinHeadWarriorYecatsmailbox.gif"),
        },
    };
}
