const entities = {
	ArrayEntity: require('./WebEntities/arrayEntity.js'),
	ChoiceEntity: require('./WebEntities/choiceEntity.js'),
	ChoiceValueEntity: require('./WebEntities/choiceValueEntity.js'),
	CommandEntity: require('./WebEntities/commandEntity.js'),
	ConfigEntity: require('./WebEntities/configEntity.js'),
	CooldownEntity: require('./WebEntities/cooldownEntity.js'),
	DynamicArrayEntity: require('./WebEntities/dynamicArrayEntity.js'),
	DynamicAssetArrayEntity: require('./WebEntities/dynamicAssetArrayEntity.js'),
	DynamicObjectEntity: require('./WebEntities/dynamicObjectEntity.js'),
	FixedArrayEntity: require('./WebEntities/fixedArrayEntity.js'),
	ObjectEntity: require('./WebEntities/objectEntity.js'),
	SimpleObjectEntity: require('./WebEntities/simpleObjectEntity.js'),
	StaticObjectEntity: require('./WebEntities/staticObjectEntity.js'),
	UserEntity: require('./WebEntities/userEntity.js'),
	UserFilterEntity: require('./WebEntities/userFilterEntity.js'),
	UserFilter_BaseEntity: require('./WebEntities/userFilter_BaseEntity.js'),
	UserFilter_IsAtLeastModEntity: require('./WebEntities/userFilter_IsAtLeastModEntity.js'),
	UserFilter_IsModEntity: require('./WebEntities/userFilter_IsModEntity.js'),
	UserFilter_IsOneOfEntity: require('./WebEntities/userFilter_IsOneOfEntity.js'),
	UserFilter_IsSubEntity: require('./WebEntities/userFilter_IsSubEntity.js'),
	UserFilter_IsUserEntity: require('./WebEntities/userFilter_IsUserEntity.js'),
	AssetEntity: require('./WebEntities/Assets/assetEntity.js'),
	AssetFileEntity: require('./WebEntities/Assets/assetFileEntity.js'),
	ImageFileEntity: require('./WebEntities/Assets/imageFileEntity.js'),
	MultiAssetEntity: require('./WebEntities/Assets/multiAssetEntity.js'),
	SingleDataEntity: require('./WebEntities/Assets/singleDataEntity.js'),
	SoundFileEntity: require('./WebEntities/Assets/soundFileEntity.js'),
	FunctionEntity: require('./WebEntities/Functions/functionEntity.js'),
	FilterEntity: require('./WebEntities/Functions/Filters/filterEntity.js'),
	ResponseChoiceEntity: require('./WebEntities/Functions/Responses/responseChoiceEntity.js'),
	ResponseEntity: require('./WebEntities/Functions/Responses/responseEntity.js'),
	Response_ChatEntity: require('./WebEntities/Functions/Responses/response_ChatEntity.js'),
	Response_ConsoleEntity: require('./WebEntities/Functions/Responses/response_ConsoleEntity.js'),
	TriggerChoiceEntity: require('./WebEntities/Functions/Triggers/triggerChoiceEntity.js'),
	TriggerEntity: require('./WebEntities/Functions/Triggers/triggerEntity.js'),
	Trigger_CommandEntity: require('./WebEntities/Functions/Triggers/trigger_CommandEntity.js'),
	Trigger_ShortcutEntity: require('./WebEntities/Functions/Triggers/trigger_ShortcutEntity.js'),
	ImageEffectEntity: require('./WebEntities/ImageEffects/imageEffectEntity.js'),
	ImageEffect_DunDunDunEntity: require('./WebEntities/ImageEffects/imageEffect_DunDunDunEntity.js'),
	ImageEffect_GlowEntity: require('./WebEntities/ImageEffects/imageEffect_GlowEntity.js'),
	ImageEffect_ShadowEntity: require('./WebEntities/ImageEffects/imageEffect_ShadowEntity.js'),
	KeyEntity: require('./WebEntities/Keys/keyEntity.js'),
	KeyShortcutEntity: require('./WebEntities/Keys/keyShortcutEntity.js'),
	KeyShortcutsEntity: require('./WebEntities/Keys/keyShortcutsEntity.js'),
	LogLevelEntity: require('./WebEntities/LogLevel/logLevelEntity.js'),
	LogLevel_BaseEntity: require('./WebEntities/LogLevel/logLevel_BaseEntity.js'),
	LogLevel_DebugEntity: require('./WebEntities/LogLevel/logLevel_DebugEntity.js'),
	LogLevel_ErrorEntity: require('./WebEntities/LogLevel/logLevel_ErrorEntity.js'),
	LogLevel_InfoEntity: require('./WebEntities/LogLevel/logLevel_InfoEntity.js'),
	LogLevel_WarnEntity: require('./WebEntities/LogLevel/logLevel_WarnEntity.js'),
	BooleanEntity: require('./WebEntities/Values/booleanEntity.js'),
	HiddenStringEntity: require('./WebEntities/Values/hiddenStringEntity.js'),
	IntegerEntity: require('./WebEntities/Values/integerEntity.js'),
	NaturalNumberEntity: require('./WebEntities/Values/naturalNumberEntity.js'),
	NumberEntity: require('./WebEntities/Values/numberEntity.js'),
	PositiveNumberEntity: require('./WebEntities/Values/positiveNumberEntity.js'),
	StringEntity: require('./WebEntities/Values/stringEntity.js'),
	ValueEntity: require('./WebEntities/Values/valueEntity.js'),
	CandyFileEntity: require('./WebEntities/candyFileEntity.js'),
	CandyInflationEntity: require('./WebEntities/candyInflationEntity.js'),
	CandyInflation_BaseEntity: require('./WebEntities/candyInflation_BaseEntity.js'),
	CandyInflation_ExponentialEntity: require('./WebEntities/candyInflation_ExponentialEntity.js'),
	CandyInflation_LinearEntity: require('./WebEntities/candyInflation_LinearEntity.js'),
	CandyInflation_NoneEntity: require('./WebEntities/candyInflation_NoneEntity.js'),
	UserGroupEntity: require('./WebEntities/userGroupEntity.js'),
	ImageCommandEntity: require('./WebEntities/imageCommandEntity.js'),
	ImageEntity: require('./WebEntities/imageEntity.js'),
	SoundEntity: require('./WebEntities/soundEntity.js'),
	UserMediaEntity: require('./WebEntities/userMediaEntity.js'),
	WelcomeEntity: require('./WebEntities/welcomeEntity.js'),
};

const factory = require('./entityFactory');
const enums = require('../enums');

function registerAll() {
	Object.values(entities).forEach(entity => {
		factory.processEntityClass(entity, 'server');
	});
}

module.exports = {
	Entities: entities,
	Factory: factory,
	RegisterAll: registerAll,
	Enums: enums,
}